# Generated by Django 5.0.3 on 2024-03-30 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('linkedId', models.IntegerField(null=True)),
                ('linkPrecedence', models.CharField(choices=[('option1', 'primary'), ('option2', 'secondary')], max_length=20)),
                ('createdAt', models.DateTimeField()),
                ('updatedAt', models.DateTimeField()),
                ('deletedAt', models.DateTimeField(null=True)),
            ],
        ),
    ]
